#!/bin/bash
set -e

# TODO: This is in a kind of weird state right now, but it works
# on at least one machine, and it is only used to test backwards
# compatibility before a release.

# To use this script on Ubuntu, you will need to first run the following:
# 
# sudo apt install ghc-7.4.2 ghc-7.6.3 ghc-7.8.4 ghc-7.10.3 ghc-8.0.2 ghc-8.2.2 ghc-8.4.4 ghc-8.6.5

declare -a ghcs_old=("7.4.2" "7.6.3" "7.8.4" "7.10.3")
declare -a ghcs_new=("8.0.2" "8.2.2" "8.4.4" "8.6.5" "8.8.4" "8.10.4")

## now loop through the above arrays
for g in "${ghcs_old[@]}"
do
   cabal build -w "/opt/ghc/bin/ghc-$g" --builddir="dist-$g" quickcheck-classes-base
done

for g in "${ghcs_new[@]}"
do
   cabal build all --builddir "dist-$g" -w "/opt/ghc/bin/ghc-$g"
   cabal build all --builddir "dist-$g-minimal" -w "/opt/ghc/bin/ghc-$g" -f-semigroupoids -f-aeson -f-semirings
done

